title: ClashOfClans Stats
description: A documentation site for ClashOfClans Stats
theme: just-the-docs
color_scheme: dark

url: https://docs.github.io/ClashOfClansStats/docs.github.io

# Code Blocks
enable_copy_code_button: true

aux_links:
  Github: https://github.com/ClashOfClansStats/main

nav_external_links:
  - title: Clash of Clans Stats on Github
    url: https://github.com/ClashOfClansStats/main
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: True # set to true to open this link in a new tab - defaults to false
